-- Sample events data for testing
INSERT INTO events (
  event_name,
  slug,
  landscape_poster,
  portrait_poster,
  date,
  time,
  duration,
  age_limit,
  event_type,
  language,
  category,
  venue,
  price,
  description,
  performers,
  creator_email
) VALUES
(
  'Travis Scott – Circus Maximus Tour Delhi',
  'travis-scott-circus-maximus-tour-delhi',
  '/Travis Scott – Circus Maximus Tour delhi landscape.avif',
  '/Travis Scott – Circus Maximus Tour delhi potrait.avif',
  '2025-12-15',
  '19:00',
  '120 min',
  'PG13',
  'event',
  'English',
  'Music',
  'Jawaharlal Nehru Stadium, Delhi',
  '₹2999',
  'Experience the electrifying performance of Travis Scott live in Delhi. The Circus Maximus Tour brings his biggest hits and spectacular stage production.',
  'Travis Scott',
  'admin@rkade.com'
),
(
  'GO GOA GONE 2',
  'go-goa-gone-2',
  '/GO GOA GONE 2 POTRAIT.jpg',
  '/GO GOA GONE 2 POTRAIT.jpg',
  '2025-11-20',
  '18:30',
  '150 min',
  'U/A',
  'movie',
  'Hindi',
  'Comedy',
  'PVR Cinemas, Select City Walk',
  '₹199',
  'The sequel to the hit comedy film. Join the gang for another hilarious adventure in Goa.',
  'Kunal Kemmu, Vir Das, Anand Tiwari',
  'admin@rkade.com'
),
(
  'Zero to One',
  'zero-to-one',
  '/zerotoone.svg',
  '/zerotoone.svg',
  '2025-10-25',
  '10:00',
  '480 min',
  'U',
  'event',
  'English',
  'Workshop',
  'IIT Delhi Campus',
  'FREE',
  'A comprehensive workshop on entrepreneurship and innovation. Learn from industry experts and successful entrepreneurs.',
  'Various Industry Experts',
  'admin@rkade.com'
),
(
  'iHGF Delhi Fair Autumn Edition',
  'ihgf-delhi-fair-autumn-edition',
  '/IHGF potrait.jpg',
  '/IHGF potrait.jpg',
  '2025-11-10',
  '10:00',
  '480 min',
  'U',
  'event',
  'English',
  'Exhibition',
  'India Expo Centre, Greater Noida',
  'FREE',
  'The largest handicrafts and gifts fair in India. Discover unique products from artisans across the country.',
  'Various Artisans',
  'admin@rkade.com'
),
(
  'East Bengal FC vs Real Kashmir FC',
  'east-bengal-fc-vs-real-kashmir-fc',
  '/East Bengal FC vs Real Kashmir FC potrait.jpg',
  '/East Bengal FC vs Real Kashmir FC potrait.jpg',
  '2025-12-01',
  '19:30',
  '90 min',
  'U',
  'sports',
  'English',
  'Football',
  'Salt Lake Stadium, Kolkata',
  '₹599',
  'Witness the thrilling match between East Bengal FC and Real Kashmir FC in the I-League.',
  'East Bengal FC, Real Kashmir FC',
  'admin@rkade.com'
),
(
  'Udgaar 2025 – Youth Cultural Festival',
  'udgaar-2025-youth-cultural-festival',
  '/Udgaar 2025.jpg',
  '/Udgaar 2025.jpg',
  '2025-12-20',
  '18:00',
  '300 min',
  'U',
  'event',
  'Hindi',
  'Music',
  'Delhi University Campus',
  '₹299',
  'Join us for the biggest youth cultural festival of the year. Music, dance, food, and fun activities.',
  'Various Artists',
  'admin@rkade.com'
),
(
  'Kantara: A Legend Chapter 1',
  'kantara-a-legend-chapter-1',
  '/Kantara.jpg',
  '/Kantara.jpg',
  '2025-11-15',
  '20:00',
  '150 min',
  'U/A',
  'movie',
  'Kannada',
  'Drama',
  'INOX Megaplex, Saket',
  '₹149',
  'Experience the epic tale of Kantara. A story of tradition, culture, and supernatural elements.',
  'Rishab Shetty, Sapthami Gowda',
  'admin@rkade.com'
),
(
  'Karan Aujla India Tour',
  'karan-aujla-india-tour',
  '/flyer.svg',
  '/flyer.svg',
  '2025-12-10',
  '19:30',
  '120 min',
  'PG13',
  'event',
  'Punjabi',
  'Music',
  'Thyagaraj Stadium, Delhi',
  '₹1999',
  'Don''t miss Karan Aujla live in concert. Experience his biggest hits and latest tracks.',
  'Karan Aujla',
  'admin@rkade.com'
)
ON CONFLICT (slug) DO NOTHING;
